name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch. Update if needed.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # Path to your Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dynoform-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/dynoform-frontend:${{ github.sha }}
